rewritting the buggy progam in f90
this makes the compiler nervous:

badfortran.f90:4:11:

    4 |   do i=1.20
      |           1
Error: Syntax error in iterator at (1)
badfortran.f90:6:5:

    6 |   enddo
      |     1
Error: Expecting END PROGRAM statement at (1)
badfortran.f90:5:13:

    5 |      print*,i
      |             1
Error: Symbol 'i' at (1) has no IMPLICIT type

The explanation: <start quote> 77 allowed any variable to be assumed
to be real or integer depending on the first letter. Specifically
variables starting with letters a–h or o–z are assumed to be
real (floating point) while variables starting with l–n are assumed
integers.  Thus in our example above the compiler assumed we had set a
new variable called “do 30 i” and set it’s value to 1.2. We then print
i, which is a different variable that has not been set and so assumes
a random value from memory, which is what was printed. Thus the famous
joke: “God is real unless declared integer”<end quote>

The lesson: *always* declare implicit none at the top of your
code. With gfortran, you could use the flag -fimplicit-none in case
you forgot (this is what will allow the compiler to find the
issue. Otherwise in Fortran 77 the error goes unoticed)